config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :authors

  resources :categories

  devise_for :users, :sign_out_via => [ :get, :delete ]
  ActiveAdmin.routes(self)

  get 'home/index'
  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role? :administrator
        can :manage, :all
    elsif user.role? :librarian
        can :manage, [Book, Category, Author, BooksAuthorsJoin, BooksCategoriesJoin]
    else
        can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    
  end
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id          :integer          not null, primary key
#  name        :string
#  avatar      :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Author < ActiveRecord::Base


	has_many :books_authors_joins
	has_many :books, :through => :books_authors_joins

	accepts_nested_attributes_for :books, :allow_destroy => true

	
	mount_uploader :avatar, ImageUploader
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id            :integer          not null, primary key
#  title         :string
#  sub_title     :string
#  image         :string
#  origin_title  :string
#  language      :string
#  pulished_year :integer
#  pages         :integer
#  cover_price   :float
#  isbn          :string
#  description   :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Book < ActiveRecord::Base

	has_many :books_authors_joins
	has_many :authors, :through => :books_authors_joins
	has_many :books_categories_joins
	has_many :categories, :through => :books_categories_joins

	accepts_nested_attributes_for :authors, :allow_destroy => true
	accepts_nested_attributes_for :categories, :allow_destroy => true

	mount_uploader :image, ImageUploader

	before_destroy :remove_join_tables

	def remove_join_tables 
		self.authors.clear
		self.categories.clear
	end
	
end

app/models/books_authors_join.rb
# == Schema Information
#
# Table name: books_authors_joins
#
#  id        :integer          not null, primary key
#  book_id   :integer
#  author_id :integer
#

class BooksAuthorsJoin < ActiveRecord::Base
	belongs_to :book
	belongs_to :author
end

app/models/books_categories_join.rb
# == Schema Information
#
# Table name: books_categories_joins
#
#  id          :integer          not null, primary key
#  book_id     :integer
#  category_id :integer
#

class BooksCategoriesJoin < ActiveRecord::Base
	belongs_to :book
	belongs_to :category
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
	has_many :books_categories_joins
	has_many :books, :through => :books_categories_joins

	accepts_nested_attributes_for :books, :allow_destroy => true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  fullname               :string
#  nickname               :string
#  avatar                 :string           default("default_normal_user_avatar.png")
#  status                 :integer          default(1)
#  role                   :string           default("borrower"), included in [administrator, librarian, borrower]
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save :before_save_user_method
  after_create :after_create_user_method

  # TODO Validate role in [administrator, librarian, borrower]
  # validate user email is unique

  mount_uploader :avatar, ImageUploader

  	def password_required?
      new_record? ? false : super
    end

    def role?(r)
        role.include? r.to_s
    end

    def before_save_user_method
      self.role = 'borrower' if self.role.blank?
    end

    def after_create_user_method
		UserMailer.registration_confirmation(self).deliver
		unless self.role? :borrower
		  self.send_reset_password_instructions
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def authenticate_active_admin_user!
        authenticate_user!
        if current_user.role? :borrower
            flash[:alert] = "You are not authorized to access this resource!"
            redirect_to root_path
        end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < InheritedResources::Base

  private

    def author_params
      params.require(:author).permit(:name, :avatar, :description, :books)
    end
end

app/controllers/books_controller.rb
class BooksController < InheritedResources::Base

  private

    def book_params
      params.require(:book).permit(:title, :sub_title, :image, :origin_title, :language, :pulished_year, :pages, :cover_price, :isbn, :description, categories_attributes: [:id, :name, :description, :_destroy], authors_attributes: [:id, :name, :avatar, :description, :_destroy])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base

  private

    def category_params
      params.require(:category).permit(:name, :description, :books)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@books = Book.all
  	@categories = Category.all
  	@authors = Author.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Avatar</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.avatar %></td>
        <td><%= author.description %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @author.avatar %>
</p>

<p>
  <strong>Description:</strong>
  <%= @author.description %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sub_title %><br>
    <%= f.text_field :sub_title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :origin_title %><br>
    <%= f.text_field :origin_title %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :pulished_year %><br>
    <%= f.number_field :pulished_year %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.number_field :pages %>
  </div>
  <div class="field">
    <%= f.label :cover_price %><br>
    <%= f.text_field :cover_price %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Sub title</th>
      <th>Image</th>
      <th>Origin title</th>
      <th>Language</th>
      <th>Pulished year</th>
      <th>Pages</th>
      <th>Cover price</th>
      <th>Isbn</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.sub_title %></td>
        <td><%= book.image %></td>
        <td><%= book.origin_title %></td>
        <td><%= book.language %></td>
        <td><%= book.pulished_year %></td>
        <td><%= book.pages %></td>
        <td><%= book.cover_price %></td>
        <td><%= book.isbn %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<html>
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
          // $("body").fadeTo(0000, 0);
          // $("body").fadeTo(300, 1);
        });
    </script>
  </head>
  
    <body>
      <div class="model-book-show-body">
        <div class="row">
          <div class="col-md-9">
            <div class="row">
              <div class="col-md-12">
                <ol class="breadcrumb">
                  <li><%= link_to "Trang chủ", root_path %></li>
                  <li><%= link_to @book.title, @book %></li>
                </ol>
              </div>
              <div class="col-md-12">
                <div class="container-fluid book-review-form">
                  <div class="col-md-3 book-image-form">
                    <%= image_tag(@book.image_url) %>
                  </div>
                  <div class="col-md-9 book-info-form">
                    <div class="col-md-12 title">
                      <%= @book.title %>
                    </div>
                    <div class="col-md-12 info">
                      <div class="row">
                        <div class="col-md-8 info-left">
                          <table class="table table-bordered">
                            <tr>
                              <td>Tiêu đề phụ</td>
                              <td><%= @book.sub_title %></td>
                            </td>
                            <tr>
                              <td>Tiêu đề gốc</td>
                              <td><%= @book.origin_title %></td>
                            </td>
                            <tr>
                              <td>Ngôn ngữ</td>
                              <td><%= @book.language %></td>
                            </td>
                            <tr>
                              <td>Năm xuất bản</td>
                              <td><%= @book.pulished_year %></td>
                            </td>
                            <tr>
                              <td>Tổng số trang</td>
                              <td><%= @book.pages %></td>
                            </td>
                            <tr>
                              <td>Giá</td>
                              <td><%= @book.cover_price %></td>
                            </td>
                          </table>
                        </div>
                        <div class="col-md-4 info-right">
                          <div class="form-group add-to-cart-form">
                            <label class="control-label" for="inputGroupSuccess3">Nhập số lượng sách</label>
                            <div class="input-group">
                              <span class="input-group-addon">Số lượng</span>
                              <input type="text" class="form-control" id="inputGroupSuccess3" aria-describedby="inputGroupSuccess3Status">
                              <span class="input-group-addon check-book-number-addon"></span>
                            </div>
                            <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-shopping-cart" style="color: white" aria-hidden="true"></span>Cho vào giỏ hàng</button>
                          </div>
                          <p style="font-size: 14px"><span class="glyphicon glyphicon-send" aria-hidden="true"></span>Chia sẻ cuốn sách này</p>
                          <button type="button" class="btn btn-info" style="background-color: #4766ae;">Facebook</button>
                          <button type="button" class="btn btn-success" style="background-color: #62a6e4;">Twitter</button>
                          <button type="button" class="btn btn-warning" style="background-color: #0aad69;">Evernote</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <div class="container-fluid book-description-form">
                  <div class="col-md-3 form-left">
                    <p class="title"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Các tác giả</p>
                    <% @book.authors.each do |author| %>
                      <div class="row sub-author">
                          <div class="col-md-8 col-md-offset-2">
                            <%= image_tag((author.avatar_url), :class => "img-circle") %>
                          </div>
                          <div class="col-md-12">
                            <p class="title"><%= author.name %></p>
                            <p class="description"><em><%= truncate author.description, length: 200 %></em></p>
                            <button type="button" class="btn btn-primary"><%= link_to "Xem thêm", author_path(author), :style => "text-decoration: none; color: white;" %></button>
                          </div>
                      </div>
                    <% end %>
                  </div>
                  <div class="col-md-9 form-right">
                    <p class="title"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Mô tả cuốn sách</p>
                    <p class="description"><%= @book.description %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <%= render "layouts/categorysidebar" %>
          </div>
        </div>
      </div>
    </body>
</html>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<html>
	<head>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script>
	      $(document).ready(function() {
	  //     	$("body").fadeTo(0000, 0);
   //        	$("body").fadeTo(300, 1);

      //     	$(".book-row img").click(function(){
		    //     $("body").fadeTo(200, 0);
		    // });

   //        	if (window.history && window.history.pushState) {
			//     window.history.pushState('forward', null, './');
			//     $(window).on('popstate', function() {
			//       $("body").fadeTo(300, 1);
			//     });
			// }

	      });
	    </script>
	</head>

	<body>
		<div class="container-fluid home-body">
			<div class="row">
				<div class="col-md-9">
					<div class="container-fluid books-group">
						<p class="book-group-title"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span>Sách mới trong tuần</p>
						<div class="row book-row">
							<% @books.each do |book| %>
								<div class="col-xs-6 col-sm-4 col-md-3">
									<div class="sub-book">
										<%= link_to image_tag(book.image_url), book %>
										<p class="title"><%= truncate book.title, length: 24 %></p>
										<div class="form-group rating-form">
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
										</div>
										<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Cho vào giỏ</button>
									</div>
								</div>
							<% end %>
						</div>
					</div>

					<div class="container-fluid books-group">
						<p class="book-group-title"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span>Sách mới cập nhật</p>

						<div class="row book-row">
							<% @books.each do |book| %>
								<div class="col-xs-6 col-sm-4 col-md-3">
									<div class="sub-book">
										<%= link_to image_tag(book.image_url), book %>
										<p class="title"><%= truncate book.title, length: 24 %></p>
										<div class="form-group rating-form">
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
										</div>
										<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Cho vào giỏ</button>
									</div>
								</div>
							<% end %>
						</div>
					</div>


				</div>

				<div class="col-md-3">
					<%= render "layouts/categorysidebar" %>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/layouts/_categorysidebar.html.erb
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/categorysidebar.css">
	</head>

	<body>
		<div class="list-group category-group">
		  <a href="#" class="list-group-item active">Sách hay dành cho bạn</a>
		  <a href="#" class="list-group-item"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>Sách nổi tiếng nhất<span class="badge">10</span></a>
		  <a href="#" class="list-group-item"><span class="glyphicon glyphicon-signal" aria-hidden="true"></span>Bình chọn cao nhất<span class="badge">20</span></a>
		  <a href="#" class="list-group-item"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>Sách trong ngày<span class="badge">36</span></a>
		  <a href="#" class="list-group-item"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>Sách trong tuần<span class="badge">41</span></a>
		  <a href="#" class="list-group-item"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>Sách trong tháng<span class="badge">15</span></a>
		  
		</div>

		<div class="list-group category-group">
			<a href="#" class="list-group-item active">Sự kiện nổi bật</a>
			<a href="#" class="list-group-item"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>Miễn phí 10 cuốn sách hôm nay<span class="badge">7</span></a>
			<a href="#" class="list-group-item"><span class="glyphicon glyphicon-leaf" aria-hidden="true"></span>Giảm giá 30% tất cả các cuốn sách<span class="badge">8</span></a>
			<a href="#" class="list-group-item"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span>Gặp gỡ nhà văn Dan Brown<span class="badge">2</span></a>
		</div>

		<div class="panel panel-primary subscribe-group">
			<div class="panel-heading">Nhận tin mới từ chúng tôi</div>
			<div class="panel-body">
			<p>Bạn là người yêu thích sách và không muốn bỏ lỡ những thông tin mới nhất về những cuốn sách đang được phát hành trên thị trường? Hãy đăng ký để nhận được những thông tin mới nhất từ chúng tôi !</p>
			<div class="form-group">
				  <input type="text" class="form-control" placeholder="Địa chỉ mail của bạn" aria-describedby="basic-addon1">
				  <input type="text" class="form-control" placeholder="Họ và tên của bạn" aria-describedby="basic-addon1">
			</div>
			<button type="button" class="btn btn-success"><span class="glyphicon glyphicon-inbox" aria-hidden="true"></span>Đăng ký</button>
			</div>
		</div>

		<div class="panel panel-success author-group">
			<div class="panel-heading">Tác giả trong ngày</div>
			<div class="panel-body">
				<div class="row">
					<% Author.all.each do |i| %>
						<div class="col-xs-6 col-sm-4 col-md-6">
							<div class="sub-author-form">
								<%= link_to image_tag(i.avatar_url(:activeadmin_author_avatar_thumb)), author_path(i) %>
								<button type="button" class="btn btn-info"><%= link_to "Xem thêm", author_path(i), :style => "text-decoration: none; color: white;" %></button>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/layouts/_rightsidebar.html.erb
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="app/assets/stylesheets/leftsidebar.css">
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

		<script>
			$(document).ready(function(){
				$(window).scroll(function(){
					if ($(this).scrollTop() > 50) {
						$('#scroll-top-btn').show(300);
					} else {
						$('#scroll-top-btn').hide(300);
					}
				});

				$('#scroll-top-btn').click(function(){
					$('html, body').animate({scrollTop : 0}, 300);
					return false;
				});

				// $("#admin-link").click(function(){
	   //              $("body").fadeTo(200, 0);
	   //          });
			});
		</script>
	</head>

	<div class="sidebar-navbar">
		<div class="form-group user-form">
			<ul>
				<% if user_signed_in? %>
					<% unless current_user.role?(:borrower) %>
						<li id="admin-li"><%= link_to "A", admin_root_path, id: "admin-link" %></span></li>
					<% end %>
				<% end %>
				<li><a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a></li>
				<li><a href="#"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a></li>
				<li><a href="#"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a></li>
				<li><a href="#"><span class="glyphicon glyphicon-gift" aria-hidden="true"></span></a></li>
			</ul>
		</div>

		<div class="form-group setting-form">
			<ul>
				<li id="scroll-top-btn"><a href="#"><span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span></a></li>
				<li><a href="#"><span class="glyphicon glyphicon-signal" aria-hidden="true"></span></a></li>
				<li><a href="#"><span class="glyphicon glyphicon-flag" aria-hidden="true"></span></a></li>
				<li><a href="#"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span></a></li>
			</ul>

		</div>

	</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Die4top Library | Your books, your knowledge </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="body-left">
		<%= render "layouts/header" %>
		<p><%= notice %></p>
		<p><%= alert %></p>
		<%= yield %>
		<%= render "layouts/footer" %>
	</div>
	<div class="body-right">
		<%= render "layouts/rightsidebar" %>
	</div>
</body>
</html>